# Generated by Django 5.0.1 on 2024-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pageviews',
            field=models.BigIntegerField(default=0),
        ),
    ]
