# Generated by Django 5.0.1 on 2024-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_customuser_total_balance_customuser_pageviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_pages',
            field=models.BigIntegerField(default=0),
        ),
    ]
