# Generated by Django 5.0.1 on 2024-05-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_customuser_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
